<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>tbtl</string>
   </array>
  <key>name</key>
  <string>tbtl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.tbtl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#keywords</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.tbtl</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(DATABASE)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.tbtl</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(`)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.tbtl</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.tbtl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>comments__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>comments__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s:\s)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>( ! )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(# )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(- )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(@)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*\ )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\?\ )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(% )</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\!)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-)</string>
          <key>name</key>
          <string>string.control.tbtl</string>
        </dict>
       </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(^[A-Z_]+\b.*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.tbtl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>keyword.control.tbtl</string>
          <key>end</key>
          <string>()</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.tbtl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>strings__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
